# Generated by Django 2.2.16 on 2022-07-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220726_1725"),
        ("users", "0003_auto_20220729_1059"),
    ]

    operations = []
