# Generated by Django 2.2.16 on 2022-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0002_auto_20220723_0928"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["id"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["id"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.TextField(),
        ),
    ]
