# Generated by Django 4.0.6 on 2022-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0002_genretitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="genre",
        ),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(to="titles.genre"),
        ),
    ]
