# Generated by Django 4.0.6 on 2022-07-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0003_remove_title_genre_title_genre"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenreTitle",
        ),
    ]
