# Generated by Django 2.2.16 on 2022-07-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220722_1826"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-id"]},
        ),
    ]
